title: "DaCubeKing's Blog"
author: "Adalie"
description: "College Student from California that loves tech and programming."

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "hi@adalie.me"
twitter_username: "DaCubeKing"
github_username: "adaliea"
linkedin_username: "adaliea"
#facebook_username: username
#flickr_username: username
instagram_username: DaCubeKing
#pinterest_username: username
youtube_username: DaCubeKing
#googleplus_username: +username

show_excerpts: true

theme: "minima"

#rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-minifier

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other

header_pages:
  - reading.html
  - archive.md

jekyll-minifier:
  exclude:
    - "css/index.css"
exclude:
  - packages.json
  - tsconfig.json
  - package-lock.json
  - ts_out

keep_files:
  - ts_out


sass:
  style: compressed
  sass_dir: _sass

url: "https://dacubeking.com"