title: "Varun's Space to Talk to the Internet"
author: "Varun A"
description: "I'm a 18 year old High School student from California. I love coding and everything computers. I'm currently the programming lead for an FRC team, Team 3476 - Code Orange"

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "me@dacubeking.com"
twitter_username: "DaCubeKing"
github_username: "varun7654"
linkedin_username: "varun-ahuja-50330619b"
#facebook_username: username
#flickr_username: username
instagram_username: DaCubeKing
#pinterest_username: username
youtube_username: DaCubeKing
#googleplus_username: +username

theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
