title: "Adalie's Blog"
author:
  name: "Adalie"
  email: hi@adalie.com
description: >
  College Student from California that loves tech and programming.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "hi@adalie.me"
twitter_username: "DaCubeKing"
github_username: "adaliea"
linkedin_username: "adaliea"
#facebook_username: username
#flickr_username: username
instagram_username: DaCubeKing
#pinterest_username: username
youtube_username: DaCubeKing
#googleplus_username: +username



remote_theme: "jekyll/minima@1fe0fbfb5347fb4e047696d3b7479c04ed0051bc"


show_excerpts: true

theme: "minima"

#rss: rss

minima:
  nav_pages:
    - reading.html
    - archive.html
    - blankfiller.md

  social_links:
    - title: Github
      icon: github
      url: "https://github.com/adaliea"
    - title: Bluesky
      icon: bluesky
      url: "https://bsky.app/profile/adalie.me"
    - title: Twitter
      icon: twitter
      url: "https://twitter.com/dacubeking"
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/adaliea/"
    - title: Instagram
      icon: instagram
      url: "https://www.instagram.com/dacubeking/"
    - title: Youtube
      icon: youtube
      url: "https://youtube.com/DaCubeKing"
  hide_site_feed_link: true
  skin: auto
  show_excerpts: true


kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-minifier

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other

exclude:
  - packages.json
  - tsconfig.json
  - package-lock.json
  - ts_out

keep_files:
  - ts_out


sass:
  style: compressed
  sass_dir: _sass


jekyll-minifier:
  exclude:
    - "assets/css/*"
url: "https://dacubeking.com"