title: "DaCubeKing's Blog"
author: "Varun A"
description: "I'm a 20-year-old College Sophomore from California. I love coding and everything technology."

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "me@dacubeking.com"
twitter_username: "DaCubeKing"
github_username: "varun7654"
linkedin_username: "varun7654"
#facebook_username: username
#flickr_username: username
instagram_username: DaCubeKing
#pinterest_username: username
youtube_username: DaCubeKing
#googleplus_username: +username

theme: "minima"

#rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-minifier

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other

header_pages:
  - reading.md
  - archive.md

jekyll-minifier:
  exclude:
    - "css/index.css"
exclude:
  - packages.json
  - tsconfig.json
  - package-lock.json
  - ts_out

keep_files:
  - ts_out


sass:
  style: compressed
  sass_dir: _sass